export struct FileEntry {
    name: string,
    is-dir: bool,
}

export struct KeyData {
    key: string,
    value: string,
    unit: string,
    unit-options: [string],
    is-valid: bool,
}

export enum LineState {
    invalid,
    valid,
    running,
    done,
}

export struct LineItem {
    title: string,
    state: LineState,
    data: [KeyData],
}

export enum ActionType {
    add-line,
    value-changed,
    tab-next-field,
    tab-prev-field,
    debounced-field-check,
    unit-changed,
    line-type-changed,
    remove-line,
    switch-list,
    cycle-list-next,
    cycle-list-prev,
    add-list,
    remove-list,
    save-list,
    load-list,
    navigate-dir,
    exit,
    validate-before-save
}

export struct Action {
    action-type: ActionType,
    schema-name: string,
    line-index: int,
    key-data-index: int,
    new-value: string,
}
